string[] parameters
---
float32 time_elapsed
---
#Taken from the navigateToPose of nav2
geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
int16 number_of_recoveries
float32 distance_remaining
