/identify_action_server:
  ros__parameters:
    pic_rate: 1
    goal_obj: "fire hydrant"
    det_threshold: 10

/slam_action_server:
  ros__parameters:
    number_of_loops: 3

/arborist_node:
  ros__parameters:
    max_objects_per_second: 0.2
    mission_qa_window: 20
    bt_filename: "onlyID.xml"
